name: Checks for system dependency for given Ruby gem and installs if needed
inputs:
  gem-name:
    required: true
    description: "Name of the gem that requires system dependency "
  required-library:
    required: true
    description: "Name of the library to be installed (use a space-delimited string for multiple libraries)"
  package-manager:
    required: false
    description: "Name of package manager"
    default: "apt-get"

runs:
  using: composite
  steps:
    - name: Check for ${{ inputs.library-name }}  dependency
      shell: bash
      id: gemfile
      run: |
        echo "COUNT=$(grep ${{ inputs.gem-name }} Gemfile* | wc -l)" >> $GITHUB_OUTPUT
    - name: Check if .gemspec exists
      if: steps.gemfile.outputs.COUNT == 0
      id: gemspec
      run: |
        # Need to set shell opts to avoid returning the glob string in the array
        shopt -s nullglob
        gemspecs=(*.gemspec)
        if (( ${#gemspecs[@]} == 1)); then
          echo "COUNT=$(grep memcached ${gemspecs[0]} | wc -l)"
        fi
    - name: Install ${{ inputs.required-library }}
      if: ${{ steps.gemfile.outputs.COUNT > 0 || steps.gemspec.outputs.COUNT > 0 }}
      shell: bash
      run: |
        sudo ${{ inputs.package-manager }} -y install ${{ inputs.required-library }}
