name: Checks for system dependency for given Ruby gem and installs if needed
inputs:
  gem-name:
    required: true
    description: "Name of the gem that requires system dependency "
  required-library:
    required: true
    description: "Name of the library to be installed (use a space-delimited string for multiple libraries)"
  package-manager:
    required: false
    description: "Name of package manager"
    default: "apt-get"

runs:
  using: composite
  steps:
    - name: Check for ${{ inputs.library-name }}  dependency
      shell: bash
      run: |
        echo "dependency=$(grep ${{ inputs.gem-name }} Gemfile* | wc -l)" >> $GITHUB_ENV
    - name: Install ${{ inputs.required-library }}
      if: env.dependency > 0
      shell: bash
      run: |
        sudo ${{ inputs.package-manager }} -y install ${{ inputs.required-library }}
